apiVersion: v1
kind: Service
metadata:
  name: saktt-service
spec:
  ports:
  - name: saktt-service-80
    port: 80
    targetPort: 9090
    protocol: TCP
  selector:
    app: saktt
  type: ClusterIP
